### ISSUE TITLE
Create a react project and define environment accordingly

### ISSUE THREAD

**Issue by NaorHaba** [Argum-com/argum#11]
@benny-n let's create a react basic implementation and download packages we believe we all need to have to start working immediately on Friday
Then, we can think if we want to add the packages to the docker with @M-Wittner

**Comment by benny-n** [comment]
Are we sure React is the right tool for the job?
I think that Next.js would be a more valid choice given the project's scope, of course it's open for debate if someone disagrees

**Comment by NaorHaba** [comment]
Can you explain the differences for us dummies?

**Comment by benny-n** [comment]
Basically from what I know Next.js is more suited for large, non-SPA apps.
But this requires more investigation, we should have a discussion about this.

**Comment by benny-n** [comment]
> Basically from what I know Next.js is more suited for large, non-SPA apps. But this requires more investigation, we should have a discussion about this.

Relating to that, I think the first thing we need to figure out is if we want an SPA or not.

https://www.reddit.com/r/webdev/comments/165cmcy/when_do_single_page_applications_spas_become_not/

Top comment from this thread:

> 
> This answer is in the name: "Application".
> 
> Is what you're building more of a website or application?
> 
> If it's 80% a content website, then you don't need an SPA.
> 
> If it's 80% an application then consider building it as an SPA.

This is the question we need to answer.

**Comment by NaorHaba** [comment]
React SPA is the final decision for the project
initial commit was done
